<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="MonoGame.ImGuiNet" Version="1.0.5" />
    <!-- MonoGame.ImGuiNet как PackageReference больше не нужен — заменяем Reference ниже -->
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MonoGame.ImGuiNet">
      <HintPath>$(NuGetPackageRoot)monogame.imguinet\1.0.5\Monogame.ImGuiNet.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Render\Render.csproj" />
    <ProjectReference Include="..\Runtime\Runtime.csproj" />
  </ItemGroup>

</Project>