<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
		<PackageReference Include="xunit.v3" Version="4.*" />
		<PackageReference Include="xunit.runner.visualstudio" Version="4.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RunTime\Runtime.csproj" />
	</ItemGroup>

	<!-- Копируем .tmj в подпапку Data рядом с тестовой сборкой -->
	<ItemGroup>
		<None Include="RunTime\Data\*.tmj"
		      Link="Data\%(Filename)%(Extension)"
		      CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>